// https://cast.clrtd.com/deck/4MCMT
module.exports = {
  "black": [
    {"text": "The Great Barrier Reef is\nunder dire threat from\noverfishing, toxic runoff,\nand _____ ."},
    {"text": "The most memorable image from\nthis year's Sydney Mardi Gras\nwas _____ on a float."},
    {"text": "Australia: where even _____\ncan kill you."},
    {"text": "Channel 9 is pleased to\npresent its new variety show,\n\"Hey Hey It's _____ \","},
    {"text": "How is Tony Abbott stopping\nthe boats? _____ ."},
    {"text": "In Australia, _____ is twice\nas big and twice as deadly."},
    {"text": "Crikey! I've never seen _____\nlike this! Let's get a bit\ncloser."},
    {"text": "Oi! Show us _____ !"},
    {"text": "Well may we say \"God save the\nQueen\", because nothing will\nsave _____ ."},
    {"text": "What broke up the original\nWiggles? _____ ."},
    {"text": "I waited six months at the\nChristmas Island Immigration\nDetention Centre and all I\ngot was _____ ."},
    {"text": "Come to Melbourne, where you\ncan relax in our world-famous\nspas, experience the\nnightlife, or simply enjoy\n_____ by the poolside."},
    {"text": "This year, Australia's\nparliament will officially\napologize to the Aboriginal\npopulation for _____ ."},
    {"text": "What should harden the fuck\nup? _____ ."},
    {"text": "I love a sunburnt country; a\nland of sweeping plains, of\nragged mountain ranges, of\n_____ ."},
    {"text": "Australians all let us\nrejoice, For we are young and\n_____ ."},
    {"text": "Good work, Mr Squiggle! It\nlooks just like _____ ."},
    {"text": "Clive Palmer's new theme park\nputs _____ on display for all\nto see."},
    {"text": "Australians have voted to\nreplace the Union Jack with\nan image of _____ on the\nnational flag."},
    {"text": "Nesquik® makes _____ fun!"},
    {"text": "The new Scienceworks\nexhibition gives kids a rare\nlook inside of _____ ."},
    {"text": "Are you thinking what I'm\nthinking B1? I think I am B2:\nIt's _____ time."}
  ],
  "white": [
    {"text": "Queen Elizabeth's immaculate\nanus."},
    {"text": "Russell Crowe's shitty band."},
    {"text": "The big fucking hole in the\nozone layer."},
    {"text": "A marsupial that shits cubes."},
    {"text": "Copping a shag in the back of\na ute."},
    {"text": "All four prongs of an\nechidna's penis."},
    {"text": "A didgeridildo."},
    {"text": "Harold Holt's bloated corpse."},
    {"text": "Massive, widespread drought."},
    {"text": "A six-point plan to stop the\nboats."},
    {"text": "The entire cast of Neighbors."},
    {"text": "Tony Abbott in budgie\nsmugglers."},
    {"text": "9 out of 10 of the most\nvenomous snakes in the world."},
    {"text": "The White Australia Policy."},
    {"text": "Mooning the Queen."},
    {"text": "More sheep than people."},
    {"text": "Pingers."},
    {"text": "New Zealand's orc problem."},
    {"text": "55 million cane toads."},
    {"text": "Contagious face cancer."},
    {"text": "A ute muster."},
    {"text": "Breaking the Silence."},
    {"text": "Bali belly."},
    {"text": "Dropping a baby down a\nthunderbox."},
    {"text": "A knife that's really a\nknife."},
    {"text": "Finding my mate Andy in a\nblokes mag."},
    {"text": "Myxomatosis."},
    {"text": "A double plugger blowout."},
    {"text": "Total control of the media."},
    {"text": "Tasmanians."},
    {"text": "Kiwis."},
    {"text": "People smuggling."},
    {"text": "Slip-Slop-Slap."},
    {"text": "Steve Irwin."},
    {"text": "A meat raffle."},
    {"text": "Chundering into a kangaroo's\npouch."},
    {"text": "Japanese whalers."},
    {"text": "Profound respect and\nappreciation for indigenous\nculture."},
    {"text": "A jolly swagman."},
    {"text": "The Stolen Generations."},
    {"text": "All kinds of skin cancer."},
    {"text": "The Bush."},
    {"text": "Clive Palmer opinions."},
    {"text": "A literal tornado of fire."},
    {"text": "Coon™ cheese."},
    {"text": "Skippy the Bush Kangaroo."},
    {"text": "A suppository of wisdom."},
    {"text": "Sorry, this content cannot be\nviewed in your region."},
    {"text": "Cashed-up bogans."},
    {"text": "Restoring the monarchy."},
    {"text": "A sensible gun control\npolicy."},
    {"text": "Rupert Murdoch."},
    {"text": "Seppos."},
    {"text": "Play-by-play commentary by\nRichie Benaud."},
    {"text": "Americanisation."},
    {"text": "The Great Emu War."},
    {"text": "Mr. Squiggle, the Man from\nthe Moon."},
    {"text": "Quokka soccer."},
    {"text": "Good-natured, fun-loving\nAussie racism."},
    {"text": "Boat people: half boat, half\nhuman."},
    {"text": "Ned Kelly's helmet."},
    {"text": "Reading the future in Rupert\nMurdoch's jowl folds."},
    {"text": "Gina Rinehart."},
    {"text": "Making up for hundreds of\nyears of oppression with one\nday of apologizing."},
    {"text": "Doing a Harold Holt."},
    {"text": "A fair go."},
    {"text": "Drinking Fosters ironically."},
    {"text": "Getting glassed."},
    {"text": "A stingray barb through the\nchest."},
    {"text": "A saliva-stained poster of\nHugh Jackman."},
    {"text": "A five-litre goon bag."},
    {"text": "Guano."},
    {"text": "Sheep dags."},
    {"text": "The dingo that ate my baby."},
    {"text": "Huggable loveable koalas with\nchlamydia."},
    {"text": "Six months at the Christmas\nIsland Immigration Detention\nCentre."},
    {"text": "Australia's next Chiko Chick."},
    {"text": "A redback under the dunny\nseat."},
    {"text": "John Howard's eyebrows."},
    {"text": "ISnack 2.0."},
    {"text": "Moldy fairy bread."},
    {"text": "Boat people."},
    {"text": "Populate or perish."},
    {"text": "A sick burnout."},
    {"text": "Our first Koala Prime\nMinister."},
    {"text": "Playing sillybuggers."},
    {"text": "Having a Golden Gaytime."},
    {"text": "A four-by-four full of dead\nbackpackers."},
    {"text": "˙ɐᴉlɐɹʇsnɐ."}
  ]
}